### ISSUE TITLE
Implement Academy CLF

### ISSUE THREAD

**Issue by scoopxyz** [imageworks/OpenColorIO#491] opened 2017-12-15 16:55 UTC
Self-explanatory and much needed, add momentum here.

**Comment by hodoulp** [comment] 2018-01-02 19:52
Part of OCIO v2

**Comment by dbr** [comment] 2018-01-18 23:02
(CLF being [Common LUT Format](https://github.com/ampas/CLF))

**Comment by hodoulp** [comment] 2018-05-29 13:35
@BernardLefebvre is working on that.

**Comment by michdolan** [comment] 2019-07-21 06:12
#656 Added CLF read support. Sufficient to close this?

**Comment by BernardLefebvre** [comment] 2019-07-22 12:54
I am still working on CLF write support.

**Comment by doug-walker** [comment] 2019-07-22 17:59
You could close this as a duplicate of #610.  And as Bernard wrote, we were waiting on the writer to close that one.

**Comment by michdolan** [comment] 2019-07-22 19:15
As Doug stated, closing this as duplicate of #610 .

**Closed by michdolan** 2019-07-22 19:15 UTC
Labels: Feature Request, v2.0
